import {
  Controller,
  Post,
  Body,
  HttpCode,
  Logger,
  UseInterceptors,
  UploadedFile,
  BadRequestException,
  NotFoundException,
} from '@nestjs/common';
import { FileInterceptor } from '@nestjs/platform-express';
import {
  ApiTags,
  ApiOperation,
  ApiResponse,
  ApiBody,
  ApiConsumes,
} from '@nestjs/swagger';
import { JobService } from '../job/job.service';
import { DbmlToCsvService } from './dbml-to-csv.service';
import { GenerateDbmlCsvDto } from './dto/generate-dbml-csv.dto';
import * as fs from 'fs';

@ApiTags('dbml-to-csv')
@Controller('dbml-to-csv')
export class DbmlToCsvController {
  private readonly logger = new Logger(DbmlToCsvController.name);

  constructor(
    private readonly dbmlToCsvService: DbmlToCsvService,
    private readonly jobService: JobService,
  ) {}

  @Post('generate-from-job')
  @HttpCode(202)
  @ApiOperation({
    summary: 'Convert DBML to CSV from a completed DBML generation job',
    description: `Starts an asynchronous job to convert a DBML file (generated by json-dbml or smartsheet-dbml endpoints) into a structured CSV format.

## How It Works

1. **Provide a Job ID** of a previously completed \`dbml-generation\` job (from \`json-dbml\` or \`smartsheet-dbml\` endpoints).
2. The system retrieves the DBML file from that job.
3. It parses the DBML content and extracts table and field metadata.
4. It generates a CSV file with 9 columns containing all the extracted information.
5. The output is a new job that, once completed, will contain the CSV file.

## CSV Output Columns

The generated CSV contains the following columns:

1. **Table Name** - The name of the table (in snake_case for SmartSheet, original name for Airtable)
2. **Original Sheet Name** - Original sheet name from SmartSheet (empty for Airtable tables)
3. **Path** - Path hierarchy from SmartSheet (empty for Airtable tables)
4. **Table Description** - Business description of the table (without technical name prefix)
5. **Field Name** - The name of the field
6. **Field Type** - The type of the field (e.g., \`singleLineText\`, \`formula\`, \`date\`)
7. **Field Description** - Business description of the field (from \`business_desc\`)
8. **technical_desc** - Technical description of the field
9. **read_only** - Whether the field is read-only (\`true\` or \`false\`)

## Usage Flow

1. **Generate DBML** using \`POST /json-dbml/generate-async\` or \`POST /smartsheet-dbml/generate\`
2. **Wait for completion** by checking \`GET /jobs/{jobId}/status\`
3. **Convert to CSV** using this endpoint with the DBML job ID
4. **Check status** at \`GET /jobs/{newJobId}/status\`
5. **Download CSV** from \`GET /jobs/{newJobId}/download\` when status is "completed"

## Example Response

\`\`\`json
{
  "jobId": "a1b2c3d4-e5f6-7890-1234-567890abcdef",
  "status": "pending",
  "message": "DBML to CSV conversion process started.",
  "statusUrl": "/jobs/a1b2c3d4-e5f6-7890-1234-567890abcdef/status",
  "resultUrl": "/jobs/a1b2c3d4-e5f6-7890-1234-567890abcdef/result"
}
\`\`\`

## Notes

- The source job must be of type \`dbml-generation\` and have status \`completed\`
- The DBML file must contain valid table and field definitions
- Each field in the DBML will generate one row in the CSV
- Table information is repeated for each field row`,
  })
  @ApiBody({
    type: GenerateDbmlCsvDto,
    description: 'The job ID of the completed DBML generation job to convert.',
  })
  @ApiResponse({
    status: 202,
    description: 'CSV conversion job accepted and processing started.',
    schema: {
      type: 'object',
      properties: {
        jobId: {
          type: 'string',
          example: 'a1b2c3d4-e5f6-7890-1234-567890abcdef',
          description: 'Unique identifier for the new CSV conversion job',
        },
        status: {
          type: 'string',
          example: 'pending',
          description: 'Current status of the job',
        },
        message: {
          type: 'string',
          example: 'DBML to CSV conversion process started.',
          description: 'Human-readable message about the job status',
        },
        statusUrl: {
          type: 'string',
          example: '/jobs/a1b2c3d4-e5f6-7890-1234-567890abcdef/status',
          description: 'URL to check the job status',
        },
        resultUrl: {
          type: 'string',
          example: '/jobs/a1b2c3d4-e5f6-7890-1234-567890abcdef/result',
          description: 'URL to download the result when completed',
        },
      },
    },
  })
  @ApiResponse({
    status: 400,
    description: 'Invalid request - job not found, not completed, or wrong job type.',
    schema: {
      type: 'object',
      properties: {
        statusCode: { type: 'number', example: 400 },
        message: { type: 'string', example: 'Source job is not completed. Current status: processing' },
      },
    },
  })
  @ApiResponse({
    status: 404,
    description: 'Source job not found.',
    schema: {
      type: 'object',
      properties: {
        statusCode: { type: 'number', example: 404 },
        message: { type: 'string', example: 'Source job with ID abc123 not found.' },
      },
    },
  })
  async generateCsvFromJob(@Body() dto: GenerateDbmlCsvDto) {
    const newJobId = this.jobService.createJob('dbml-to-csv');

    setTimeout(() => {
      this.jobService.processAsyncJob(newJobId, async (updateProgress) => {
        try {
          // Get source job
          const sourceJob = this.jobService.getJob(dto.jobId);
          if (!sourceJob) {
            throw new NotFoundException(
              `Source job with ID ${dto.jobId} not found.`,
            );
          }

          // Validate job is completed
          if (sourceJob.status !== 'completed') {
            throw new BadRequestException(
              `Source job ${dto.jobId} is not completed. Current status: ${sourceJob.status}`,
            );
          }

          // Validate job type is dbml-generation
          if (sourceJob.jobType !== 'dbml-generation') {
            throw new BadRequestException(
              `Source job ${dto.jobId} is not a 'dbml-generation' job. Job type: ${sourceJob.jobType}`,
            );
          }

          // Get DBML file path
          const dbmlPath = this.jobService.getJobResultPath(dto.jobId);
          if (!dbmlPath || !fs.existsSync(dbmlPath)) {
            throw new NotFoundException(
              `DBML file for job ${dto.jobId} not found.`,
            );
          }

          // Read DBML content
          updateProgress(5, 'Reading DBML file');
          const dbmlContent = fs.readFileSync(dbmlPath, 'utf-8');

          // Convert to CSV
          return await this.dbmlToCsvService.parseDbmlToCsv(
            dbmlContent,
            updateProgress,
          );
        } catch (error) {
          this.logger.error(
            `DBML to CSV conversion failed for source job ${dto.jobId}: ${error.message}`,
          );
          return JSON.stringify(
            {
              error: true,
              message: error.message,
              details: {
                sourceJobId: dto.jobId,
                timestamp: new Date().toISOString(),
                errorType: error.constructor.name,
              },
            },
            null,
            2,
          );
        }
      });
    }, 0);

    return {
      jobId: newJobId,
      status: 'pending',
      message: 'DBML to CSV conversion process started.',
      statusUrl: `/jobs/${newJobId}/status`,
      resultUrl: `/jobs/${newJobId}/result`,
    };
  }

  @Post('generate-from-file')
  @HttpCode(202)
  @UseInterceptors(FileInterceptor('file'))
  @ApiConsumes('multipart/form-data')
  @ApiOperation({
    summary: 'Convert DBML to CSV from an uploaded DBML file',
    description: `Starts an asynchronous job to convert an uploaded DBML file into a structured CSV format.

## How It Works

1. **Upload a DBML file** containing table and field definitions.
2. The system parses the DBML content and extracts table and field metadata.
3. It generates a CSV file with 9 columns containing all the extracted information.
4. The output is a new job that, once completed, will contain the CSV file.

## CSV Output Columns

The generated CSV contains the following columns:

1. **Table Name** - The name of the table (in snake_case for SmartSheet, original name for Airtable)
2. **Original Sheet Name** - Original sheet name from SmartSheet (empty for Airtable tables)
3. **Path** - Path hierarchy from SmartSheet (empty for Airtable tables)
4. **Table Description** - Business description of the table (without technical name prefix)
5. **Field Name** - The name of the field
6. **Field Type** - The type of the field (e.g., \`singleLineText\`, \`formula\`, \`date\`)
7. **Field Description** - Business description of the field (from \`business_desc\`)
8. **technical_desc** - Technical description of the field
9. **read_only** - Whether the field is read-only (\`true\` or \`false\`)

## Usage Flow

1. **Upload DBML file** using this endpoint
2. **Check status** at \`GET /jobs/{jobId}/status\`
3. **Download CSV** from \`GET /jobs/{jobId}/download\` when status is "completed"

## File Format

The uploaded file must be a valid DBML file with the following structure:

\`\`\`dbml
Table table_name {
    field_name field_type [note: 'business desc: ..., technical desc: ..., readonly field: true/false']
    note: '### table_name Table (id: ...) - Table description'
}
\`\`\`

## Example Response

\`\`\`json
{
  "jobId": "a1b2c3d4-e5f6-7890-1234-567890abcdef",
  "status": "pending",
  "message": "DBML to CSV conversion process started from file.",
  "statusUrl": "/jobs/a1b2c3d4-e5f6-7890-1234-567890abcdef/status",
  "resultUrl": "/jobs/a1b2c3d4-e5f6-7890-1234-567890abcdef/result"
}
\`\`\`

## Notes

- The file must contain valid DBML syntax
- Each field in the DBML will generate one row in the CSV
- Table information is repeated for each field row`,
  })
  @ApiBody({
    schema: {
      type: 'object',
      required: ['file'],
      properties: {
        file: {
          type: 'string',
          format: 'binary',
          description: 'A DBML file containing table and field definitions.',
        },
      },
    },
  })
  @ApiResponse({
    status: 202,
    description: 'CSV conversion job accepted and processing started.',
    schema: {
      type: 'object',
      properties: {
        jobId: {
          type: 'string',
          example: 'a1b2c3d4-e5f6-7890-1234-567890abcdef',
          description: 'Unique identifier for the new CSV conversion job',
        },
        status: {
          type: 'string',
          example: 'pending',
          description: 'Current status of the job',
        },
        message: {
          type: 'string',
          example: 'DBML to CSV conversion process started from file.',
          description: 'Human-readable message about the job status',
        },
        statusUrl: {
          type: 'string',
          example: '/jobs/a1b2c3d4-e5f6-7890-1234-567890abcdef/status',
          description: 'URL to check the job status',
        },
        resultUrl: {
          type: 'string',
          example: '/jobs/a1b2c3d4-e5f6-7890-1234-567890abcdef/result',
          description: 'URL to download the result when completed',
        },
      },
    },
  })
  @ApiResponse({
    status: 400,
    description: 'No file uploaded or invalid DBML format.',
    schema: {
      type: 'object',
      properties: {
        statusCode: { type: 'number', example: 400 },
        message: { type: 'string', example: 'No file uploaded. Please upload a file with the key "file".' },
      },
    },
  })
  async generateCsvFromFile(@UploadedFile() file: Express.Multer.File) {
    if (!file) {
      throw new BadRequestException(
        'No file uploaded. Please upload a file with the key "file".',
      );
    }

    const newJobId = this.jobService.createJob('dbml-to-csv');
    const fileContent = file.buffer.toString('utf-8');

    setTimeout(() => {
      this.jobService.processAsyncJob(newJobId, async (updateProgress) => {
        try {
          return await this.dbmlToCsvService.parseDbmlToCsv(
            fileContent,
            updateProgress,
          );
        } catch (error) {
          this.logger.error(
            `DBML to CSV conversion failed from file upload: ${error.message}`,
          );
          return JSON.stringify(
            {
              error: true,
              message: error.message,
              details: {
                fileName: file.originalname,
                timestamp: new Date().toISOString(),
                errorType: error.constructor.name,
              },
            },
            null,
            2,
          );
        }
      });
    }, 0);

    return {
      jobId: newJobId,
      status: 'pending',
      message: 'DBML to CSV conversion process started from file.',
      statusUrl: `/jobs/${newJobId}/status`,
      resultUrl: `/jobs/${newJobId}/result`,
    };
  }
}
